"use client";
import { useState } from "react";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import type { Resource, ReviewStatus } from "@/lib/resources/types";

export function ReviewList({ initial }: { initial: Resource[] }) {
  const [items,setItems]=useState(initial); const [status,setStatus]=useState<ReviewStatus|"all">("pending"); const [editing,setEditing]=useState<string|null>(null); const [message,setMessage]=useState(""); const visible=items.filter(item=>status==="all"||item.status===status);
  async function mutate(id:string, body:object) { const response=await fetch(`/api/admin/resources/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)}); if(!response.ok){setMessage("操作失败，请检查内容后重试。");return false;} const data=await response.json() as {resource:Resource}; setItems(current=>current.map(item=>item.id===id?data.resource:item)); return true; }
  async function review(id:string, action:"publish"|"reject") { if(await mutate(id,{action})) setMessage(action==="publish"?"资源已发布。":"投稿已拒绝。"); }
  async function save(event:React.FormEvent<HTMLFormElement>, item:Resource) { event.preventDefault(); const data=new FormData(event.currentTarget); const patch={name:data.get("name"),description:data.get("description"),recommendation:data.get("recommendation")}; if(await mutate(item.id,{action:"edit",patch})){setEditing(null);setMessage("修改已保存。");} }
  return <><div className="mt-6 flex flex-wrap gap-2">{(["pending","published","rejected","all"] as const).map(value=><button key={value} type="button" onClick={()=>setStatus(value)} className={status===value?"category-pill category-pill-active":"category-pill"}>{value==="pending"?"待审核":value==="published"?"已发布":value==="rejected"?"已拒绝":"全部"} ({value==="all"?items.length:items.filter(i=>i.status===value).length})</button>)}</div><p aria-live="polite" className="mt-4 text-sm font-semibold text-[var(--forest-soft)]">{message}</p><div className="mt-4 grid gap-4">{visible.map(item=><article key={item.id} className="rounded-2xl border border-border bg-card p-5">{editing===item.id?<form onSubmit={(event)=>save(event,item)} className="grid gap-3"><label className="text-sm font-bold">网站名称<Input name="name" defaultValue={item.name} minLength={2} maxLength={80} required className="mt-1"/></label><label className="text-sm font-bold">网站简介<Textarea name="description" defaultValue={item.description} minLength={20} maxLength={300} required className="mt-1"/></label><label className="text-sm font-bold">推荐理由<Textarea name="recommendation" defaultValue={item.recommendation} minLength={20} maxLength={500} required className="mt-1"/></label><div className="flex gap-2"><button type="button" onClick={()=>setEditing(null)} className="category-pill">取消</button><button type="submit" className="rounded-lg bg-primary px-4 py-2 text-sm font-bold text-primary-foreground">保存修改</button></div></form>:<><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase text-accent">{item.category} · {item.priceType}</p><h2 className="mt-1 text-xl font-bold">{item.name}</h2><a href={item.url} target="_blank" rel="noopener noreferrer" className="mt-1 block text-sm text-[var(--forest-soft)] underline">{item.url}</a></div>{item.status==="pending"&&<div className="flex flex-wrap gap-2"><button type="button" onClick={()=>setEditing(item.id)} className="rounded-lg border border-border px-3 py-2 text-sm font-bold">编辑</button><button type="button" onClick={()=>review(item.id,"reject")} className="rounded-lg border border-border px-3 py-2 text-sm font-bold">拒绝</button><button type="button" onClick={()=>review(item.id,"publish")} className="rounded-lg bg-primary px-3 py-2 text-sm font-bold text-primary-foreground">批准发布</button></div>}</div><p className="mt-4 leading-7 text-muted-foreground">{item.description}</p><p className="mt-3 rounded-xl bg-secondary p-3 text-sm"><strong>推荐理由：</strong>{item.recommendation}</p></>}</article>)}{!visible.length&&<p className="rounded-2xl border border-dashed border-border p-10 text-center text-muted-foreground">当前没有相关投稿。</p>}</div></>;
}
